def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

def yoVersion = "3.1.1"
def generatorVersion = "4.2.2"

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-nodejs10-angular:${odsImageTag}",
) { context ->

  stage("init yo") {
    sh "npm install -g yo@${yoVersion} && npm install -g generator-node-express-typescript@${generatorVersion}"
    sh "yo --generators"
  }

  stage("init Project") {
      sh "sh ${context.sourceDir}/init.sh --project ${context.projectId} --component ${context.componentId} --group ${context.group}"
  }

  odsQuickstarterStageCopyFiles(context)

  odsQuickstarterStageCreateOpenShiftResources(
    context,
    [directory: 'common/ocp-config/component-environment']
  )
  odsQuickstarterStageRenderJenkinsfile(context)
  
  odsQuickstarterStageRenderSonarProperties(context)
}
