def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-base:${odsImageTag}",
) { context ->

  odsQuickstarterStageCopyFiles(context)

  stage('Setup OpenShift resources') {
    sh "sh common/scripts/create-ds-component.sh -p ${context.projectId} -c ${context.componentId} -nh ${context.nexusHost} -nu ${context.nexusUsername} -np ${context.nexusPassword} --force"
    for (def env : ['dev', 'test']) {
      sh """oc patch bc ${context.componentId} --type=json --patch '
        [{"op":
          "replace", "path": "/spec/resources",
          "value": {
            "limits":{"cpu":"1","memory":"2Gi"},
            "requests":{"cpu":"500m","memory":"1Gi"}
          }
        }]' -n ${context.projectId}-${env}"""
    }
  }

  odsQuickstarterStageRenderJenkinsfile(context)
}
