def odsNamespace = ''
def odsGitRef = ''
def odsImageTag = ''
def sharedLibraryRef = ''
def agentImageTag = ''

node {
  odsNamespace = env.ODS_NAMESPACE ?: 'ods'
  odsGitRef = env.ODS_GIT_REF ?: 'master'
  odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
  sharedLibraryRef = env.SHARED_LIBRARY_REF ?: odsImageTag
  agentImageTag = env.AGENT_IMAGE_TAG ?: odsImageTag
}

library("ods-jenkins-shared-library@${sharedLibraryRef}")

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-base:${agentImageTag}",
) { context ->

  odsQuickstarterStageCopyFiles(context)

  stage('Setup OpenShift resources') {
    sh """sh common/scripts/create-ds-component.sh \
      --project ${context.projectId} \
      --component ${context.componentId} \
      --nexus-url ${context.nexusUrl} \
      --nexus-username ${context.nexusUsername} \
      --non-interactive"""
  }

  odsQuickstarterStageRenderJenkinsfile(context)

}
