apiVersion: v1
kind: Template
parameters:
- name: ODS_BITBUCKET_PROJECT
  description: Bitbucket project name.
  value: opendevstack
- name: NEXUS_URL
  description: "Your Nexus Instance"
  required: true
- name: NEXUS_AUTH
  description: "Your Nexus Authentication credentials: username:password"
  required: true
- name: REPO_BASE
  required: true
- name: ODS_IMAGE_TAG
  required: true
  value: latest
- name: ODS_GIT_REF
  required: true
  value: production
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-slave-nodejs12
    labels:
      app: jenkins-slave-nodejs12
  spec:
    dockerImageRepository: jenkins-slave-nodejs12
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-slave-nodejs12
    labels:
      app: jenkins-slave-nodejs12
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-slave-nodejs12:${ODS_IMAGE_TAG}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
    runPolicy: Serial
    source:
      contextDir: common/jenkins-slaves/nodejs12/docker
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-quickstarters.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
          - name: nexusUrl
            value: ${NEXUS_URL}
          - name: nexusAuth
            value: ${NEXUS_AUTH}
        from:
          kind: ImageStreamTag
          name: jenkins-slave-base:${ODS_IMAGE_TAG}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
