@Library('ods-mro-jenkins-shared-library@production')
@Library('ods-jenkins-shared-library@production')

/*
 * Use classic pipeline here because of blue ocean (1.18+)
 * rendering bugs with declarative pipelines.
 */ 
node {
    def config = [debug: true]
    mroPipeline(config)
}
