apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-agent-golang
parameters:
- name: ODS_BITBUCKET_PROJECT
  description: Bitbucket project name.
  value: opendevstack
- name: REPO_BASE
  required: true
- name: ODS_IMAGE_TAG
  required: true
  value: latest
- name: ODS_GIT_REF
  required: true
- name: JENKINS_AGENT_DOCKERFILE_PATH
  value: Dockerfile.ubi8
  description: Dockerfile variant to use
- name: GO_DISTRIBUTION_URL
  value: https://go.dev/dl/go1.23.0.linux-amd64.tar.gz
  description: URL pointing to go binary
- name: GOLANG_CI_VERSION
  value: v1.60.1
  description: version of go linter runner
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: jenkins-agent-golang
    labels:
      app: jenkins-agent-golang
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-golang:${ODS_IMAGE_TAG}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
        ephemeral-storage: "8Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
        ephemeral-storage: "5Gi"
    runPolicy: Serial
    source:
      contextDir: common/jenkins-agents/golang/docker
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-quickstarters.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: ${JENKINS_AGENT_DOCKERFILE_PATH}
        from:
          kind: ImageStreamTag
          name: jenkins-agent-base:${ODS_IMAGE_TAG}
        buildArgs:
          - name: goDistributionUrl
            value: ${GO_DISTRIBUTION_URL}
          - name: golangciVersion
            value: ${GOLANG_CI_VERSION}
      type: Docker
    successfulBuildsHistoryLimit: 5
