def odsGitRef = env.ODS_GIT_REF ?: 'production'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-scala:${odsImageTag}",
) { context ->

  stage("init scala akka project") {
    sh "cd ${context.sourceDir}; sh ./init.sh --project ${context.projectId} --component ${context.componentId} --group ${context.group}"
  }
  odsQuickstarterStageCreateOpenShiftResources(
    context,
    [directory: 'common/ocp-config/component-environment']
  )
  odsQuickstarterStageRenderJenkinsfile(context)
  
  odsQuickstarterStageRenderSonarProperties(context)
}
