def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
def odsMainBitbucketProject = env.ODS_BITBUCKET_PROJECT ?: 'opendevstack'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-base:${odsImageTag}",
) { context ->

  odsQuickstarterStageCopyFiles(context)

  stage('Configure metadata.yml for project') {
    sh "sed 's|@project_id@|'${context.projectId}'|g' ${context.sourceDir}/metadata.yml.tmpl > ${context.componentId}/metadata.yml"
  }

  odsQuickstarterStageRenderJenkinsfile(context)

  stage('Setup OpenShift resources') {
    dir(context.sourceDir) {
      sh """./create-ocp-resources.sh \
        --project ${context.projectId} \
        --component ${context.componentId} \
        --bitbucket ${context.bitbucketUrl} \
        --ods-namespace ${odsNamespace} \
        --ods-image-tag ${odsImageTag} \
        --docker-registry ${context.dockerRegistry}
        --bitbucket-ods-project ${odsMainBitbucketProject}
      """
    }
  }
}
