def odsNamespace = ''
def odsGitRef = ''
def odsImageTag = ''
def sharedLibraryRef = ''
def agentImageTag = ''

node {
  odsNamespace = env.ODS_NAMESPACE ?: 'ods'
  odsGitRef = env.ODS_GIT_REF ?: 'master'
  odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
  sharedLibraryRef = env.SHARED_LIBRARY_REF ?: odsImageTag
  agentImageTag = env.AGENT_IMAGE_TAG ?: odsImageTag
}

library("ods-jenkins-shared-library@${sharedLibraryRef}")

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-base:${agentImageTag}",
) { context ->

  odsQuickstarterStageCopyFiles(context)

  stage('Configure metadata.yml for project') {
    sh "sed 's|@project_id@|'${context.projectId}'|g' ${context.sourceDir}/metadata.yml.tmpl > ${context.componentId}/metadata.yml"
  }

  odsQuickstarterStageRenderJenkinsfile(context)

  stage('Setup OpenShift resources') {
    dir(context.sourceDir) {
      sh """./create-ocp-resources.sh \
        --project ${context.projectId} \
        --component ${context.componentId} \
        --bitbucket ${context.bitbucketUrl} \
        --ods-namespace ${odsNamespace} \
        --ods-image-tag ${odsImageTag} \
        --docker-registry ${context.dockerRegistry}
      """
    }
  }
}
