FROM opendevstackorg/ods-jenkins-agent-base-centos7:latest

LABEL maintainer="Sebastian Titakis <sebastian.titakis@boehringer-ingelheim.com>"

# Labels consumed by Red Hat build service
LABEL com.redhat.component="jenkins-agent-maven-rhel7-docker" \
      name="openshift3/jenkins-agent-maven-rhel7" \
      version="3.6" \
      architecture="x86_64" \
      release="4" \
      io.k8s.display-name="Jenkins agent Maven" \
      io.k8s.description="The jenkins agent maven image has the maven tools on top of the jenkins agent base image." \
      io.openshift.tags="openshift,jenkins,agent,maven"

ARG nexusUrl
ARG nexusUsername
ARG nexusPassword

ENV HOME=/home/jenkins \
    GRADLE_USER_HOME=/home/jenkins/.gradle \
    JAVA_HOME=/usr/lib/jvm/jre

# Container support is now integrated in Java 11, the +UseCGroupMemoryLimitForHeap option has been pruned
ENV JAVA_TOOL_OPTIONS="-XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true"

# Workaroud we use when running behind proxy
# Basically we put the proxy certificate in certs folder
# COPY certs/* /etc/pki/ca-trust/source/anchors/
# RUN update-ca-trust force-enable && update-ca-trust extract

COPY yum.repos.d/adoptium-temurin.repo /etc/yum.repos.d/
RUN rm -fv /etc/yum.repos.d/CentOS-Media.repo /etc/yum.repos.d/origin-local-release.repo && \
    sh -c "echo 'centos' > /etc/yum/vars/osname" && \
    sed -i 's@^\s*enabled\s*=.*$@enabled = 1@g' /etc/yum.repos.d/CentOS-Sources.repo && \
    sed -i 's@^\s*enabled\s*=.*$@enabled = 0@g' /etc/yum.repos.d/CentOS-Vault.repo && \
    sed -i 's@^\s*enabled\s*=.*$@enabled = 0@g' /etc/yum.repos.d/adoptium-temurin.repo && \
    sed -i 's@http://cbs.centos.org/@https://cbs.centos.org/@g' /etc/yum.repos.d/* && \
    grep -ri '^\s*\(name\|enabled\)\s*=' /etc/yum.repos.d/*

# Install Maven & java 11 and java 17
# Note: use java scripts are executed to test the scripts but also use-j11.sh in called 2nd place to set is as default version
RUN yum -y --skip-broken update && \
    yum install -y epel-release && \
    yum install -y java-11-openjdk-devel maven-3.5.4 && \
    yum install -y --enablerepo Adoptium temurin-17-jdk && \
    yum updateinfo -t -y && \
    yum repolist -t -y && \
    sh -c "yum list installed | grep -i '\(java\|jdk\)'" && \
    yum clean all -y && rm -rf /var/cache/yum

# Copy use java scripts.
COPY use-j*.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/use-j*.sh && \
    chmod ugo+s /usr/local/bin/use-j*.sh && \
    sh -c 'chmod ugo+s $(which alternatives)' && \
    ls -la /usr/local/bin/use-j*.sh && \
    echo "--- STARTS JDK 11/17 TESTS ---" && \
    use-j17.sh && \
    use-j11.sh && \
    echo "--- ENDS JDK 11/17 TESTS ---"

# Install Maven
ENV MAVEN_VERSION=3.5.4
ENV BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
RUN mkdir -p /usr/share/maven /usr/share/maven/ref && \
    curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 && \
    rm -f /tmp/apache-maven.tar.gz && \
    ln -s /usr/share/maven/bin/mvn /usr/bin/mvn && \
    mkdir -p $HOME/.m2 && \
    mvn --version
ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_CONFIG=$HOME/.m2

ADD ./contrib/settings.xml $HOME/.m2/

COPY set_maven_proxy.sh /tmp/set_maven_proxy.sh
COPY set_gradle_proxy.sh /tmp/set_gradle_proxy.sh

RUN mkdir -p $HOME/.m2 && \
    mkdir -p $GRADLE_USER_HOME && mkdir -p /tmp/gradle/wrapper && \
    mvn -v && \
    chmod +x /tmp/set_maven_proxy.sh && \
    chmod +x /tmp/set_gradle_proxy.sh && \
    mv $HOME/.m2/settings.xml $HOME/.m2/settings.xml.orig && \
    /tmp/set_maven_proxy.sh && \
    xpr=$(cat /tmp/mvn_proxy) && \
    xpr="${xpr//\//\\/}" && \
    xpr="${xpr//|/\\|}" && \
    cat $HOME/.m2/settings.xml.orig | sed -e "s|<proxies>|<proxies>$xpr|g" > $HOME/.m2/settings.xml && \
    sed -i "s/__NEXUS_USER/$nexusUsername/gi" $HOME/.m2/settings.xml && \
    sed -i "s/__NEXUS_PW/$nexusPassword/gi" $HOME/.m2/settings.xml && \
    sed -i "s|__NEXUS_URL|$nexusUrl|gi" $HOME/.m2/settings.xml && \
    cat $HOME/.m2/settings.xml

# install gradle ..
ADD gradlew /tmp/gradlew
RUN mkdir -p /tmp/gradle/wrapper
ADD gradle/* /tmp/gradle/wrapper
RUN ls /tmp/gradle/wrapper

# set java proxy var
COPY set_gradle_proxy.sh /tmp/set_gradle_proxy.sh
RUN chmod 777 /tmp/set_gradle_proxy.sh

RUN mkdir -pv $GRADLE_USER_HOME && \
    /tmp/set_gradle_proxy.sh

RUN /tmp/gradlew -version && \
    sh -c "source use-j17.sh && /tmp/gradlew -version" && \
    sh -c "source use-j11.sh && /tmp/gradlew -version"

#set java proxy via JAVA_OPTS as src
RUN bash -l -c 'echo export JAVA_OPTS="$(/tmp/set_java_proxy.sh && echo $JAVA_OPTS)" >> /etc/bash.bashrc'

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME && \
    chmod -c 666 /etc/pki/ca-trust/extracted/java/cacerts && \
    ls -la /etc/pki/ca-trust/extracted/java/cacerts
USER 1001

