= Data Science Plotly Dash (ds-dash)

The project supports generation of Plotly Dash project boilerplate and quick
installation and integration of it with OpenShift CD pipelines.

== Purpose of this quickstarter

The quickstarter is provisioning a Dash boilerplate ready to be used.
The package allows easily build a Dash project, using different Python dependencies.
It contains the basic setup for Docker, Jenkins, SonarQube and OpenShift.

== What files / architecture is generated?

 ├── Jenkinsfile - This file contains Jenkins build configuration settings
 ├── files
 │   ├── docker - This folder contains Docker configuration settings
 │   │   ├── Dockerfile
 │   │   └── run.sh - This bash script solves issue with permissions for a container user
 │   └── src
 │       ├── app.py - This file is the main entry point in the project.
 │       └── requirements.txt - This file contains a list of required Python modules to run application
 └── sonar-project.properties - This file contains SonarQube configuration settings

== Frameworks used

* https://docs.python.org/3.7/tutorial/[Python 3.7]
* https://plot.ly/dash/[Dash]

== Usage - how do you start after you provisioned this quickstarter

The project should be started automatically by OpenShift. Server should be started
on the port 8080 in the debug mode.

[source,python]
----
app.run('0.0.0.0', 8080, debug=True)
----

To disable a debug mode set debug to *False*.

To run application locally - specify the next command in a console:

[source,bash]
----
python app.py
----

If you run application the first time, please install dependencies with the next
command:

[source,bash]
----
pip install -r requirements.txt
----

It is recommended when you work with a Python project use separated environment
for every of your project. For this purpose usually iis used
https://virtualenv.pypa.io/en/latest/[virtualenv] package.

[source,bash]
----
# Command install virtualenv package (run only once)
pip install virtualenv
# Creates virtual environment 'venv' (will be located in the folder venv) (run only once)
virtualenv venv

# Initiate virtual environment for the project (every time)
source venv/bin/activate

# Runs installation of required modules in the virtual environment (run only once)
pip install -r requirements.txt

# Start your application
python app.py
----

== Usage - how do you start after you provisioned this quickstarter

The quickstarter sets up two pods in OpenShift. The `ds-dash` application is routed through the https://github.com/openshift/oauth-proxy/[OpenShift OAuth proxy].

== How this quickstarter is built through jenkins

The build pipeline is defined in the `Jenkinsfile` in the project root. The main stages of the pipeline are:

. Build
. Scan for Sonarqube
. Start OpenShift build
. Deploy image to OpenShift

== Builder slave used

https://github.com/opendevstack/ods-core/tree/master/jenkins/slave-base[jenkins-slave-base]
