source 'https://rubygems.org'

source 'https://rubygems.org' do
  gem 'activesupport'
  gem 'irb'
  gem 'kitchen-terraform', '~> 7.0'
  gem 'test-kitchen'
  gem 'rspec-retry'
  gem 'aws-sdk', '~> 3'
  gem 'csv'
  gem 'mutex_m'
  gem 'syslog'
end

source 'https://rubygems.cinc.sh' do
  gem 'inspec-core'
  gem 'inspec'
  gem 'cinc-auditor-bin', '~> 5.22', '>= 5.22.55'
  gem 'unf_ext'
  gem 'chef-config'
  gem 'chef-utils'
  gem 'mixlib-install'
  gem 'mixlib-versioning'
end
