source 'https://rubygems.org' do
  gem 'activesupport'
  gem 'irb'
  gem 'kitchen-terraform', '~> 5.8.0'
  gem 'test-kitchen'
  gem 'rspec-retry'
  gem 'aws-sdk', '~> 3'
end

source 'https://packagecloud.io/cinc-project/stable' do
  gem 'inspec-core'
  gem 'inspec', '4.37.30'
  gem 'cinc-auditor-bin'
  gem 'unf_ext'
  gem 'chef-config'
  gem 'chef-utils'
  gem 'mixlib-install'
  gem 'mixlib-versioning'
end
