# add /overwrite FROM with your base image, and do whatever you like here :)
FROM docker-group-@ods_namespace@.@app_domain@/alpine:latest

RUN echo "building simple frontend container"

EXPOSE 8080

CMD ["/bin/sh", "-c", "/usr/bin/nc -lk -p 8080 -e echo -e \"HTTP/1.1 200 OK\n\nHello World!\n$(date)\""]
