FROM opendevstackorg/ods-jenkins-agent-base-ubi8:latest

# Labels consumed by Red Hat build service
LABEL com.redhat.component="jenkins-agent-nodejs-12-rhel7-container" \
      name="openshift4/jenkins-agent-nodejs-12-rhel7" \
      architecture="x86_64" \
      io.k8s.display-name="Jenkins Agent Nodejs" \
      io.k8s.description="The jenkins agent nodejs image has the nodejs tools on top of the jenkins slave base image." \
      io.openshift.tags="openshift,jenkins,agent,nodejs" \
      maintainer="openshift-dev-services+jenkins@redhat.com"

ARG nexusUrl
ARG nexusAuth

ENV NODEJS_VERSION=12 \
    YARN_VERSION=1.22.5 \
    NPM_CONFIG_PREFIX=$HOME/.npm-global \
    PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/node_modules/.bin/:$HOME/.npm-global/bin/:$PATH \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

ENV INSTALL_PKGS="make gcc-c++ GConf2 nss libXScrnSaver alsa-lib "
ENV INSTALL_CENTOS_PKGS="nodejs nodejs-nodemon xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel"

# Workaroud we use when running behind proxy
# Basically we put the proxy certificate in certs folder
# COPY certs/* /etc/pki/ca-trust/source/anchors/
# RUN update-ca-trust force-enable && update-ca-trust extract

COPY contrib/bin/configure-agent /usr/local/bin/configure-agent

COPY yum.repos.d/*.repo /etc/yum.repos.d/
RUN sed -i 's@^\s*enabled\s*=.*$@enabled = 1@g' /etc/yum.repos.d/*.repo \
    && sed -i 's@^\s*enabled\s*=.*$@enabled = 0@g' /etc/yum.repos.d/centos*.repo \
    && sed -i 's@^\s*enabled\s*=.*$@enabled = 0@g' /etc/yum.repos.d/google-chrome*.repo \
    && grep -i '\(name\|enabled\)' /etc/yum.repos.d/*.repo

# Install Python 3 (because node-gyp, an ionic dependency, uses it) and set it as default
RUN yum install -y python3 python3-pip || true
# update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
RUN bash -c "python -V 2>&1 | grep -q 'Python 3.*' || update-alternatives --install /usr/bin/python python /usr/bin/python3 1 " && \
    bash -c "python -V 2>&1 | grep 'Python 3.*' || echo 'ERROR: Invalid python version'"

# Generate machine ID
RUN dbus-uuidgen > /etc/machine-id

# Install NodeJS (https://rpm.nodesource.com/setup_12.x does NOT work)
RUN yum install -y $INSTALL_PKGS && \
    yum module enable -y nodejs:${NODEJS_VERSION} && \
    yum install -y --setopt=tsflags=nodocs --disableplugin=subscription-manager --enablerepo centos-appstream $INSTALL_CENTOS_PKGS && \
    rpm -V $INSTALL_PKGS

# Install Yarn
# https://classic.yarnpkg.com/en/docs/install
RUN curl -o- -sSL https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION

# Install Cypress dependencies
# https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements
RUN yum repolist \
    && yum install -y --enablerepo google-chrome --enablerepo centos-appstream --enablerepo centos-baseos google-chrome-stable \
    && yum clean all -y

RUN npm config set registry=$nexusUrl/repository/npmjs/ && \
    npm config set always-auth=true && \
    npm config set _auth=$(echo -n $nexusAuth | base64) && \
    npm config set email=no-reply@opendevstack.org && \
    npm config set ca=null && \
    npm config set strict-ssl=false && \
    yarn config set registry $nexusUrl/repository/npmjs/ -g && \
    echo node version: $(node --version) && \
    echo npm version: $(npm --version) && \
    echo npx version: $(npx --version) && \
    echo yarn version: $(yarn --version)

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
