def odsGitRef = env.ODS_GIT_REF ?: 'production'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

def ionicVersion = "3.9.2"

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-base:${odsImageTag}",
) { context ->

  stage("update ionic cli") {
    sh "npm install -g ionic@${ionicVersion} && ionic version"
  }

  stage("init ionic project") {
    sh "sh ${context.sourceDir}/init.sh --project ${context.projectId} --component ${context.componentId} --group ${context.group}"
  }

  odsQuickstarterStageCreateOpenShiftResources(
    context,
    [directory: 'common/ocp-config/component-environment']
  )

  odsQuickstarterStageRenderJenkinsfile(context)

  odsQuickstarterStageRenderSonarProperties(context)
}
