FROM opendevstackorg/ods-jenkins-agent-base-ubi8:latest

LABEL maintainer="Erhard Wais <erhard.wais@boehringer-ingelheim.com>, Frank Joas <frank.joas@boehringer-ingelheim.com>, Josef Hartmann <josef.hartmann@boehringer-ingelheim.com>, Steve Taylor <steve.taylor@boehringer-ingelheim.com>"

# Labels consumed by Red Hat build service
LABEL com.redhat.component="jenkins-agent-terraform-ubi8-docker" \
      name="openshift/jenkins-agent-terraform-ubi8" \
      version="0.1" \
      architecture="x86_64" \
      release="1" \
      io.k8s.display-name="Jenkins Agent Terraform" \
      io.k8s.description="The jenkins agent image has terraform and other tools on top of the jenkins agent base image." \
      io.openshift.tags="openshift,jenkins,agent,terraform,aws,azure"

ARG nexusUrl
ARG nexusAuth
ARG NPMJS_REGISTRY_FLAG

ENV TERRAFORM_VERSION=1.4.6 \
    TERRAFORM_CONFIG_INSPECT_VERSION=0.2.0 \
    TERRAFORM_DOCS_VERSION=v0.16.0 \
    RUBY_VERSION=3.2.2 \
    PACKER_VERSION=1.8.7 \
    CONSUL_VERSION=1.15.2 \
    TFENV_VERSION=3.0.0 \
    TFLINT_VERSION=0.46.1 \
    NODEJS_VERSION=18 \
    BUNDLER_VERSION=2.4.13 \
    AGE_VERSION=1.1.1 \
    GEM_HOME=/opt/bundle \
    RBENV_ROOT=/opt/rbenv \
    RBENV_SHELL=bash \
    NPM_CONFIG_CAFILE=/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem

ENV INSTALL_PKGS="yum-utils gcc make git-core zlib zlib-devel gcc-c++ patch \
    python3.9 python3.9-pip python3.9-setuptools \
    python3.11 python3.11-pip python3.11-setuptools \
    readline \
    libffi-devel libyaml-devel openssl-devel make bzip2 bzip2-devel autoconf curl sqlite-devel xz \
    jq parallel"
ENV INSTALL_DNF_PKGS="readline-devel bison automake libtool"
ENV PATH=/opt/tfenv/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/node/bin:$PATH
ENV HOME=/home/jenkins

RUN sh -c "rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm || true"
COPY python_requirements /tmp/requirements.txt

# Workaroud we use when running behind proxy
# Basically we put the proxy certificate in certs folder
# COPY certs/* /etc/pki/ca-trust/source/anchors/
# RUN update-ca-trust force-enable && update-ca-trust extract

COPY yum.repos.d/almalinux9.repo /etc/yum.repos.d/almalinux.repo
RUN sed -i 's@^\s*enabled\s*=.*$@enabled = 1@g' /etc/yum.repos.d/*.repo \
    && sed -i 's@^\s*enabled\s*=.*$@enabled = 0@g' /etc/yum.repos.d/almalinux.repo \
    && grep -i '\(name\|enabled\)' /etc/yum.repos.d/*.repo

RUN set -x \
    && dnf -y repolist \
    && dnf -y install $INSTALL_PKGS \
    && dnf -y install --enablerepo almalinux-baseos --enablerepo almalinux-appstream $INSTALL_DNF_PKGS \
    && dnf clean all

# Download, compile, and install Python 3.8 from source
RUN cd /usr/src && \
    wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz && \
    tar xzf Python-3.8.12.tgz && \
    cd Python-3.8.12 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    rm -f /usr/src/Python-3.8.12.tgz

# Install pip, setuptools, and devel packages for Python 3.8
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3.8 get-pip.py && \
    rm get-pip.py && \
    python3.8 -m pip install --upgrade setuptools 

RUN curl -sSL "https://bootstrap.pypa.io/pip/3.6/get-pip.py" -o "get-pip.py" \
    && python3 get-pip.py

# Upgrade pip
RUN pipVersions=( pip3 pip3.8 pip3.9 pip3.11 ); \
    for pipV in "${pipVersions[@]}"; \
    do \
        if [ ! -z ${nexusHost} ] && [ ! -z ${nexusAuth} ]; \
        then $pipV config set global.index-url https://${nexusAuth}@${nexusHost}/repository/pypi-all/simple \
            && $pipV config set global.trusted-host ${nexusHost} \
            && $pipV config set global.extra-index-url https://pypi.org/simple; \
        fi; \
        $pipV config set global.cert /etc/ssl/certs/ca-bundle.crt && \
        $pipV install --upgrade pip --user && \
        $pipV install virtualenv pycodestyle; \
    done; \
    alternatives --set python /usr/bin/python3.11 \
    && alternatives --set python3 /usr/bin/python3.11

# Install python requirements
RUN python3.8 -m pip install -r /tmp/requirements.txt \
    && python3.9 -m pip install -r /tmp/requirements.txt \
    && python3.11 -m pip install -r /tmp/requirements.txt \
    && rm -f /tmp/requirements.txt

# Install awscli2
RUN curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip -qq awscliv2.zip \
    && ./aws/install \
    && rm -f awscliv2.zip \
    && rm -Rf ./aws

# Install awssamcli
RUN curl -sSL "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o "awssam.zip" \
    && unzip -qq -d awssam awssam.zip \
    && ./awssam/install && rm -f awssam.zip && rm -Rf ./awssam

# Install NodeJS
RUN INSTALL_NODE="nodejs nodejs-nodemon" \
    && curl -fsSL https://rpm.nodesource.com/setup_${NODEJS_VERSION}.x  | bash - \
    && yum install -y --setopt=tsflags=nodocs --disableplugin=subscription-manager $INSTALL_NODE \
    && rpm -V $INSTALL_NODE \
    && yum clean all -y \
    && npm config set registry=$nexusUrl/repository/npmjs/ \
    && npm config set //${nexusUrl#*://}/repository/npmjs/:_auth=$(echo -n $nexusAuth | base64) \
    && npm config set email=no-reply@opendevstack.org \
    && npm config set strict-ssl=true

# Install aws cdk
RUN npm install -g ${NPMJS_REGISTRY_FLAG} aws-cdk \
    && node --version \
    && cdk --version

# Install terraform
RUN wget -q -O /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" \
    && unzip /tmp/terraform.zip -d /usr/local/bin \
    && rm -rf /tmp/terraform.zip \
    && terraform -h

# Install tfenv
RUN umask 0002 && cd /opt && git clone --branch v${TFENV_VERSION} https://github.com/tfutils/tfenv.git \
    && TFENV_CURL_OUTPUT=0 /opt/tfenv/bin/tfenv install ${TERRAFORM_VERSION} \
    && /opt/tfenv/bin/tfenv use ${TERRAFORM_VERSION} \
    && chown -R 1001:0 /opt/tfenv \
    && chmod +x /opt/tfenv/bin/* \
    && terraform -version \
    && tfenv list

# Install tflint
RUN wget -q -O /tmp/tflint.zip "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip" \
    && unzip /tmp/tflint.zip -d /usr/local/bin \
    && rm -rf /tmp/tflint.zip \
    && tflint --version

# Install packer
RUN wget -q -O /tmp/packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" \
    && unzip /tmp/packer.zip -d /usr/local/bin \
    && rm -rf /tmp/packer.zip \
    && packer --version

# Install terraform-config-inspect
RUN wget -q -O /tmp/terraform-config-inspect.tar.gz https://github.com/nichtraunzer/terraform-config-inspect/releases/download/v${TERRAFORM_CONFIG_INSPECT_VERSION}/terraform-config-inspect_${TERRAFORM_CONFIG_INSPECT_VERSION}_linux_amd64.tar.gz \
    && tar zxpf /tmp/terraform-config-inspect.tar.gz -C /usr/local/bin/ \
    && rm -f /tmp/terraform-config-inspect.tar.gz \
    && chmod 755 /usr/local/bin/terraform-config-inspect

# Install terraform-docs
RUN wget -q -O /tmp/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz \
    && tar zxpf /tmp/terraform-docs.tar.gz -C /usr/local/bin/ terraform-docs \
    && chmod +x /usr/local/bin/terraform-docs

# Install consul-cli
RUN wget -q "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip" \
    && unzip consul_${CONSUL_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && rm -f consul_${CONSUL_VERSION}_linux_amd64.zip \
    && chmod +x /usr/local/bin/consul \
    && /usr/local/bin/consul -version

# Install age
RUN wget -q -O /tmp/age.tar.gz https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz \
    && tar xzf /tmp/age.tar.gz -C /usr/local/bin \
    && rm -f /tmp/age.tar.gz

RUN chmod +t /tmp \
    && chown -R 1001:0 $HOME \
    && chmod -R g+rwX $HOME \
    && mkdir -p $GEM_HOME \
    && chmod 2770 $GEM_HOME

COPY Gemfile Gemfile.lock $GEM_HOME/

RUN chown -R 1001:0 $GEM_HOME \
    && chmod -R g+rw $GEM_HOME \
    && ls -lisa /home/jenkins $GEM_HOME

# Setup ruby env and bundler gems
# RUBY https://syslint.com/blog/tutorial/how-to-install-ruby-on-rails-with-rbenv-on-centos-7-or-rhel-7/
RUN cd /opt \
    && umask 0002 \
    && git clone https://github.com/rbenv/rbenv.git /opt/rbenv \
    && echo 'export PATH="/opt/rbenv/shims:/opt/rbenv/bin:$PATH"' >> ~/.bash_profile \
    && echo 'eval "$(rbenv init -)"' >> ~/.bash_profile \
    && source ~/.bash_profile \
    && git clone https://github.com/rbenv/ruby-build.git /opt/rbenv/plugins/ruby-build \
    && echo 'export PATH="/opt/rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bash_profile \
    && source ~/.bash_profile \
    && MAKE_OPTS='-j 4' rbenv install $RUBY_VERSION \
    && rbenv global $RUBY_VERSION \
    && gem install bundler -v $BUNDLER_VERSION \
    && RBENV_VERSION=$RUBY_VERSION gem install bundler -v $BUNDLER_VERSION \
    && bundle config default $BUNDLER_VERSION \
    && RBENV_VERSION=$RUBY_VERSION bundle config default $BUNDLER_VERSION \
    && bundle config set --global path $GEM_HOME \
    && RBENV_VERSION=$RUBY_VERSION bundle config set --global path $GEM_HOME \
    && cd $GEM_HOME \
    && BUNDLE_SILENCE_ROOT_WARNING=true bundle install --full-index --jobs=8 \
    && rm -Rf /home/jenkins/.bundle/cache

USER 1001

