FROM opendevstackorg/ods-jenkins-agent-base-ubi8:latest

LABEL maintainer="Gerard C.L. <gerard.castillo@boehringer-ingelheim.com>"

ARG rustVersion
ARG rustToolchain
ARG cargoNextestVersion
ARG cargoLlvmCovVersion
ARG cargoGenerateVersion
ARG cargoDenyVersion

ENV PATH="$HOME/.cargo/bin:$PATH"
ENV USER="rust-agent"
ENV CARGO_NEXTEST_VERSION=${cargoNextestVersion} \
    CARGO_LLVM_COV_VERSION=${cargoLlvmCovVersion} \
    CARGO_GENERATE_VERSION=${cargoGenerateVersion} \
    CARGO_DENY_VERSION=${cargoDenyVersion}

RUN yum install -y binutils cpp gcc glibc-devel glibc-headers isl kernel-headers libasan libatomic \
    libgomp libmpc libpkgconf libubsan libxcrypt-devel llvm-libs pkgconf pkgconf-m4 pkgconf-pkg-config \
    openssl-devel cpan perl-IPC-Cmd && \
    cpan install FindBin

RUN mkdir -p $HOME/.cargo/bin $HOME/.rustup && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
        -y --profile complete --default-toolchain ${rustVersion} -t ${rustToolchain} && \
    cargo -V && \
    # Download binaries and install to $HOME/.cargo/bin
    curl --proto '=https' --tlsv1.2 -fsSL https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-$CARGO_NEXTEST_VERSION/cargo-nextest-$CARGO_NEXTEST_VERSION-$rustToolchain.tar.gz | tar xzf - -C "$HOME/.cargo/bin" && \
    curl --proto '=https' --tlsv1.2 -fsSL https://github.com/cargo-generate/cargo-generate/releases/download/v$CARGO_GENERATE_VERSION/cargo-generate-v$CARGO_GENERATE_VERSION-$rustToolchain.tar.gz | tar xzf - -C "$HOME/.cargo/bin" && \
    # curl --proto '=https' --tlsv1.2 -fsSL https://github.com/taiki-e/cargo-llvm-cov/releases/download/v$CARGO_LLVM_COV_VERSION/cargo-llvm-cov-$rustToolchain.tar.gz | tar xzf - -C "$HOME/.cargo/bin" && \
    # cargo LLVM coverage crate is recommended to be compiled as it takes care to add the OS lib dependencies the proper way
    cargo install cargo-llvm-cov --locked --version $CARGO_LLVM_COV_VERSION && \
    # install cargo deny as release sources do not provide our rust toolchain target
    cargo install cargo-deny --locked --version $CARGO_DENY_VERSION && \
    cargo --version && \
    cargo nextest --version && \
    cargo llvm-cov --version && \
    cargo generate --version && \
    cargo deny --version

RUN chgrp -R 0 $HOME/.cargo $HOME/.rustup && \
    chmod -R g=u $HOME/.cargo $HOME/.rustup
