FROM opendevstackorg/ods-jenkins-agent-base-ubi8:latest

ARG goDistributionUrl=https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
ARG golangciVersion=v1.54.2

RUN yum install -y gcc gcc-c++

RUN cd /tmp && \
    curl -LfSso /tmp/go.tar.gz $goDistributionUrl && \
    tar -C /usr/local -xzf go.tar.gz && \
    rm -f /tmp/go.tar.gz && \
    cd - && \
    mkdir /go && \
    /usr/local/go/bin/go version

ENV PATH $PATH:/usr/local/go/bin
ENV GOBIN /usr/local/bin

COPY install-golangci-lint.sh /tmp/install-golangci-lint.sh
RUN /tmp/install-golangci-lint.sh -b /usr/local/bin $golangciVersion && \
    rm -f /tmp/install-golangci-lint.sh

RUN go install github.com/jstemmer/go-junit-report/v2@v2.0.0

RUN mkdir -p /home/jenkins/go && chmod g+w /home/jenkins/go

WORKDIR /go
