def odsGitRef = env.ODS_GIT_REF ?: 'production'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-maven:${odsImageTag}",
) { context ->

  odsQuickstarterStageForkODS (
  	context, 
  	[ "odsComponent" : "ods-provisioning-app" ]
  )

/*
  // @ FIXME  add once prov app OCP resources are in the new shape 
  // (https://github.com/opendevstack/ods-provisioning-app/issues/423)
  
  odsQuickstarterStageCreateOpenShiftResources(
    context, 
    [ 
      "directory" : "${context.componentId}/openshift",
      "selector" : "app=ods-provisioning-app" 
    ]
  )
*/
}
