def odsNamespace = ''
def odsGitRef = ''
def odsImageTag = ''
def sharedLibraryRef = ''
def agentImageTag = ''

node {
  odsNamespace = env.ODS_NAMESPACE ?: 'ods'
  odsGitRef = env.ODS_GIT_REF ?: 'master'
  odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
  sharedLibraryRef = env.SHARED_LIBRARY_REF ?: odsImageTag
  agentImageTag = env.AGENT_IMAGE_TAG ?: odsImageTag
}

library("ods-jenkins-shared-library@${sharedLibraryRef}")

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-base:${agentImageTag}",
) { context ->

  odsQuickstarterStageCopyFiles(context)

  odsQuickstarterStageRenderJenkinsfile(context)

  odsQuickstarterStageRenderSonarProperties(context)

  renderHelmChart(context)
}

def renderHelmChart(def context) {
  def relativeSourceFilePath = "Chart.yaml.template"
  def relativeDestinationFilePath = "chart/Chart.yaml"
  def absoluteSourceFilePath = "${context.sourceDir}/${relativeSourceFilePath}"
  def absoluteDestinationFilePath = "${context.targetDir}/${relativeDestinationFilePath}"
  sh(script: "source use-j21.sh && ./gradlew clean build --stacktrace --no-daemon && source use-j11.sh", label: "Render Helm Chart.yaml file")
}
