apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-agent-terraform-2306
parameters:
- name: ODS_BITBUCKET_PROJECT
  description: Bitbucket project name.
  value: opendevstack
- name: NEXUS_URL
  required: true
- name: NEXUS_AUTH
  required: true
- name: REPO_BASE
  required: true
- name: ODS_IMAGE_TAG
  required: true
  value: latest
- name: ODS_GIT_REF
  required: true
- name: JENKINS_AGENT_DOCKERFILE_PATH
  value: Dockerfile.ubi8
  description: Dockerfile variant to use
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: jenkins-agent-terraform-2306
    labels:
      app: jenkins-agent-terraform-2306
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-terraform-2306:${ODS_IMAGE_TAG}
    postCommit: {}
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
        ephemeral-storage: "30Gi"
      requests:
        cpu: "500m"
        memory: "5Gi"
        ephemeral-storage: "20Gi"
    runPolicy: Serial
    source:
      contextDir: common/jenkins-agents/terraform-2306/docker
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-quickstarters.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
          - name: nexusUrl
            value: ${NEXUS_URL}
          - name: nexusAuth
            value: ${NEXUS_AUTH}
        dockerfilePath: ${JENKINS_AGENT_DOCKERFILE_PATH}
        from:
          kind: ImageStreamTag
          name: jenkins-agent-base:${ODS_IMAGE_TAG}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
