def odsGitRef = env.ODS_GIT_REF ?: 'production'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

def dockerRegistry

node {
  dockerRegistry = env.DOCKER_REGISTRY
}

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-airflow:${odsImageTag}",
) { context ->

  odsQuickstarterStageCopyFiles(context)

  stage('Setup OpenShift resources') {
    sh "cd ${context.sourceDir} ; sh ./custom-create-components.sh \
      -p ${context.projectId} -c ${context.componentId} -b ${context.gitUrlHttp.split('/' + context.projectId)[0]} \
      -r ${dockerRegistry} -gr ${odsGitRef} \
      -oa 'your-openshift-apihost' -oc 'https://your-openshift-console' "
  }

  odsQuickstarterStageCreateOpenShiftResources(context)

  odsQuickstarterStageRenderJenkinsfile(context)

  odsQuickstarterStageRenderSonarProperties(context)
}
