FROM opendevstackorg/ods-jenkins-agent-base-ubi9:latest

LABEL maintainer="Gerard Castillo <gerard.castillo@boehringer-ingelheim.com>"

ARG nexusHost
ARG nexusAuth

ENV PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    UV_CA_CERTIFICATE=/etc/ssl/certs/ca-bundle.crt \
    PIP_CERT=/etc/ssl/certs/ca-bundle.crt \
    PATH=$HOME/.local/bin:$JAVA_HOME/bin:$PATH \
    UV_VERSION=0.10.9

# Set PyPI URLs and configure Python packages
RUN yum install -y autoconf automake gcc gcc-c++ openssl-devel libffi-devel && \
    curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | sh && \
    mkdir -p $HOME/.config/pip && \
    echo "[global]" > $HOME/.config/pip/pip.conf && \
    if [ -n "${nexusHost}" ] && [ -n "${nexusAuth}" ]; then \
      echo "index-url = https://${nexusAuth}@${nexusHost}/repository/pypi-all/simple" >> $HOME/.config/pip/pip.conf && \
      echo "trusted-host = ${nexusHost}" >> $HOME/.config/pip/pip.conf && \
      echo "export UV_DEFAULT_INDEX=https://${nexusAuth}@${nexusHost}/repository/pypi-all/simple" > /etc/profile.d/uv-index.sh; \
    else \
      echo "export UV_DEFAULT_INDEX=https://pypi.org/simple" > /etc/profile.d/uv-index.sh; \
    fi && \
    yum -y clean all

RUN PACKAGES="virtualenv==20.26.3 setuptools==72.2.0 Cython==3.0.11 pypandoc==1.13" && \
    for pyVersion in 3.8 3.9 3.11 3.12; do \
      uv python install $pyVersion && \
      if [ -n "${nexusHost}" ] && [ -n "${nexusAuth}" ]; then \
        uv pip install --system --break-system-packages --python $pyVersion --index-url https://${nexusAuth}@${nexusHost}/repository/pypi-all/simple --trusted-host ${nexusHost} $PACKAGES; \
      else \
        uv pip install --system --break-system-packages --python $pyVersion $PACKAGES; \
      fi; \
    done && \
    uv tool update-shell

# Enables default user to access $HOME folder
RUN chown -R 1001:0 $HOME && \
    chmod -R a+rw $HOME

USER 1001
