FROM opendevstackorg/ods-jenkins-agent-base-ubi8:latest

LABEL maintainer="Gerard Castillo <gerard.castillo@boehringer-ingelheim.com>"

ARG nexusHost
ARG nexusAuth

ENV PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    PIP_NO_CACHE_DIR=off \
    PATH=$JAVA_HOME/bin:$PATH

RUN yum module install -y python38:3.8/build && \
    yum module install -y python39:3.9/build --allowerasing && \
    yum install -y python3.11 python3.11-pip python3.11-devel python3.11-setuptools --allowerasing && \
    yum install -y python3.12 python3.12-pip python3.12-devel python3.12-setuptools --allowerasing && \
    yum install -y autoconf automake gcc-c++ openssl-devel libffi-devel && \
    yum -y clean all

RUN pipVersions=( pip3.8 pip3.9 pip3.11 pip3.12 ); \
    for pipV in "${pipVersions[@]}"; \
    do \
        if [ ! -z ${nexusHost} ] && [ ! -z ${nexusAuth} ]; \
        then $pipV config set global.index-url https://${nexusAuth}@${nexusHost}/repository/pypi-all/simple \
            && $pipV config set global.trusted-host ${nexusHost} \
            && $pipV config set global.extra-index-url https://pypi.org/simple; \
        fi; \
        $pipV config set global.cert /etc/ssl/certs/ca-bundle.crt && \
        $pipV install --upgrade pip --user && \
        $pipV install virtualenv==20.26.3 setuptools==72.2.0 Cython==3.0.11 pypandoc==1.13; \
    done;

# Enables default user to access $HOME folder
RUN chown -R 1001:0 $HOME && \
    chmod -R a+rw $HOME

USER 1001
