def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

def angularCliVersion = "8.0.3"

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-nodejs10-angular:${odsImageTag}",
) { context ->

  stage("update angular cli") {
    sh "npm install -g @angular/cli@${angularCliVersion} && ng version"
  }
  stage("init angular project") {
    sh "sh ${context.sourceDir}/init.sh --project ${context.projectId} --component ${context.componentId} --group ${context.group}"
  }

  odsQuickstarterStageCreateOpenShiftResources(
    context,
    [directory: 'common/ocp-config/component-environment']
  )

  odsQuickstarterStageRenderJenkinsfile(context)

  odsQuickstarterStageRenderSonarProperties(context)
}
