// FIX: Either move into node, or remove the node block if possible ...
def projectId = env.PROJECT_ID;
def componentId = env.COMPONENT_ID.toLowerCase();
def packageName = env.PACKAGE_NAME;
def gitUrlHttp = env.GIT_URL_HTTP
def gitUrlSsh = env.GIT_URL_SSH
def group = "org.osi";
def nexusHost = env.NEXUS_HOST;

def credentialsId = "cd-user-with-password"
// FIX: Name of quickstarter directory to be-java-springboot
// TODO: Retrieve automatically? E.g. via BuildConfig/jenkinsfilePath
def springQuickstarterBasepath = "beSpringBoot";
def dockerRegistry

node {
  dockerRegistry = env.DOCKER_REGISTRY
}

def conts = containerTemplate( 
            name: 'jnlp',
            image: "${dockerRegistry}/cd/jenkins-slave-base:2",
            workingDir: '/tmp',
            alwaysPullImage: true,
            // TODO: Check if args: '${computer.jnlpmac} ${computer.name}' is needed
            args: ''
        )

def podLabel = "quickstarter-beSpringBoot-" + projectId + "-" +componentId;


podTemplate(
      label: podLabel,
      cloud: 'openshift',
      containers: [conts],
      volumes: [],
      serviceAccount: 'jenkins'
    ) {
        node(podLabel) {
          stage('Checkout quickstarter') {
            checkout scm
          }
          stage('Install spring') {
              sh 'curl -s "https://get.sdkman.io" | bash'
              // TODO: $SPRING_CLI_VERSION is not set - fix this
              sh '/bin/bash -lc "source /home/jenkins/.sdkman/bin/sdkman-init.sh && sdk install springboot $SPRING_CLI_VERSION && spring --version"'
          }
          stage('Build spring project') {
            // TODO: Check if spring is in the PATH or think about alternative path
            sh "/home/jenkins/.sdkman/candidates/springboot/current/bin/spring init \
                --build=gradle \
                --java-version='1.8' \
                --groupId=${projectId} \
                --artifactId=${componentId} \
                --package-name='${packageName}' \
                --packaging=jar \
                --dependencies='web,jersey,data-jpa,h2,lombok,data-rest,restdocs,security' \
                  ${componentId}"
            withEnv(["COMPONENT=${componentId}","GROUP=${group}","SCRIPT_DIR=${springQuickstarterBasepath}"]) {
              sh "sh ./${springQuickstarterBasepath}/postProcessProjectsettings.sh"            
            }
          }

          stage('Setup OpenShift resources') {
            sh "sh common/scripts/create-component.sh -p ${projectId} -c ${componentId} -ne ${nexusHost} --force"
          }
          stage('Create Jenkinsfile') {
            sh "sh common/scripts/renderJenkinsTemplate.sh \
                  --source ${springQuickstarterBasepath}/files/Jenkinsfile.template \
                  --target ${componentId}/Jenkinsfile \
                  --url ${gitUrlHttp} \
                  --project-id ${projectId} \
                  --component-id ${componentId}  \
                  --component-type ${springQuickstarterBasepath}"
          }
          stage('Create sonar-project.properties') {
            sh "sh common/scripts/renderSonarqubeTemplate.sh \
                  --source ${springQuickstarterBasepath}/files/sonar-project.properties.template \
                  --target ${componentId}/sonar-project.properties \
                  --project-id ${projectId} \
                  --component-id ${componentId}  \
                  --component-type ${springQuickstarterBasepath}"
          }
          stage('Push to remote') {
            // FIX: Machine IP and cd_user credentials
            writeFile file: "/home/jenkins/.netrc", text: "machine 192.168.56.31 login cd_user password cd_user"
            sh "sh common/scripts/git_push.sh --dir ${componentId} --url ${gitUrlHttp}"
          }
      }
}






