= Data Science Jupyter Notebook

== Purpose of this quickstarter

Provision a shared Jupyter Notebook within OpenShift for rapid prototyping of data science applications using OpenShift OAuth.

== What files / architecture is generated?

----
.
├── Jenkinsfile
├── docker
│   ├── Dockerfile
│   ├── jupyter_notebook_config.json
│   ├── requirements.txt
│   └── run.sh
├── metadata.yml - Component metadata
└── release-manager.yml - Configuration file for the Release Manager
----

== Frameworks used

* https://docs.python.org/3.8[Python 3.8]
* https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/[Jupyter]

== Usage - how do you start after you provisioned this quickstarter

The quickstarter sets up two pods in OpenShift. The `ds-jupyter-notebook` instance is routed through the https://github.com/openshift/oauth-proxy/[OpenShift OAuth proxy] instance.

The directory `/opt/app-root/src/work` is created where code can be organized using installed git. +
Please consider mounting a persistent volume claim for this path. +
New python requirements are specified using the `requirements.txt`

== How this quickstarter is built through jenkins

The build pipeline is defined in the `Jenkinsfile` in the project root. The main stages of the pipeline are:

. Start OpenShift build
. Deploy image to OpenShift

== Builder agent used

https://github.com/opendevstack/ods-core/tree/master/jenkins/agent-base[jenkins-agent-base]

== Known limitions

Consider if sufficient computing resources can be provided by the OpenShift cluster.
