= Data Science R Shiny Application

== Purpose of this quickstarter

Provisions a R Shiny application within OpenShift using OpenShift OAuth.

== What files / architecture is generated?

----
.
├── Jenkinsfile - This file contains Jenkins build configuration settings
├── .pre-commit-config.yaml
├── docker - This folder contains Docker configuration settings and main R Shiny app
│   ├── Dockerfile
│   └── app.R
├── metadata.yml - Component metadata
└── release-manager.yml - Configuration file for the Release Manager
----

== Frameworks used

* https://www.tutorialspoint.com/r/index.htm[R]
* https://shiny.rstudio.com/tutorial[Shiny]

== Usage - how do you start after you provisioned this quickstarter

The quickstarter sets up two pods in OpenShift. The `ds-rshiny` application is routed through the https://github.com/openshift/oauth-proxy/[OpenShift OAuth proxy] instance.

=== Metadata

The following are typical xref:quickstarters:metadata.adoc[metadata] values that can be used for components based on this quickstarter:
Note that the xref:jenkins-shared-library:labelling.adoc[OpenShift resources will be labeled] based on this metadata.

```yaml
name: shiny
description: "Shiny is an R package that makes it easy to build interactive web apps straight from R."
supplier: https://www.rstudio.com/
version: 1.6.0
type: ods-service
runtime: r
runtimeVersion: 4.1.1
```

== How this quickstarter is built through jenkins

The build pipeline is defined in the `Jenkinsfile` in the project root. The main stages of the pipeline are:

. Start OpenShift build
. Deploy image to OpenShift

include::partials$secret-scanning-with-gitleaks.adoc

== Builder agent used

https://github.com/opendevstack/ods-core/tree/master/jenkins/agent-base[jenkins-agent-base]

== Known limitations

N/A
