:toc: macro

= OpenDevStack Quickstarters
:page-aliases: latest@ods-quickstarters:ROOT:index.adoc

toc::[]

== Overview

This repository contains quickstarters, which are basically templates that help to start out with a component quickly. The available quickstarters are:

=== Backend Quickstarter

* xref::be-gateway-nginx.adoc[Backend - Gateway/nginx]
* xref::be-golang-plain.adoc[Backend - Golang]
* xref::be-java-springboot.adoc[Backend - SpringBoot/Java]
* xref::be-typescript-express.adoc[Backend - NodeJS/Express]
* xref::be-python-flask.adoc[Backend - Python/Flask]
* xref::be-scala-akka.adoc[Backend - Scala/Akka]
* xref::airflow-cluster.adoc[Airflow]

=== Frontend Quickstarter
* xref::fe-angular.adoc[Frontend - Angular]
* xref::fe-ionic.adoc[Mobile - Ionic]
* xref::fe-react.adoc[Frontend - React]
* xref::fe-vue.adoc[Frontend - Vue]

=== Data Science Quickstarter
* xref::ds-ml-service.adoc[Data Science - Machine Learning]
* xref::ds-jupyter-notebook.adoc[Data Science - Jupyter Notebook]
* xref::ds-rshiny.adoc[Data Science - R-Shiny]

=== E2E Test Quickstarter
* xref::e2e-cypress.adoc[E2E test - Cypress]
* xref::e2e-spock-geb.adoc[E2E test - Spock / Geb]

=== ODS Contribution Quickstarter
* xref::ods-document-gen-svc.adoc[ODS Fork - Document Generation Service]
* xref::ods-provision-app.adoc[ODS Fork - Provisioning Applications]

Next to those, there is a https://github.com/opendevstack/ods-quickstarters/blob/master/boilerplates/docker-plain/README.md["blank" quickstarter] (xref::docker-plain.adoc[Backend - Docker/Plain]) allowing to start from scratch, while still providing all the OCP resources / Jenkins / SonarQube conveniences described in the following sections.

All quickstarters are used by the https://github.com/opendevstack/ods-provisioning-app[Provisioning App] to create a new component which basically consists of resources in OpenShift (typically `BuildConfig`, `ImageStream`, `DeploymentConfig` and `Service`) and a BitBucket repository.

This repository in BitBucket will contain:

* Some boilerplate code
* A `Jenkinsfile` describing how to build the component, delegating most of the work to the xref:ods-jenkins-shared-library:ROOT:index.adoc[shared library]
* A `sonar-project.properties` file configuring how the source code is analyzed by SonarQube

Next to those, each quickstarter can also provide its own https://github.com/opendevstack/ods-quickstarters/tree/master/common/jenkins-slaves[Jenkins slave images].

== Usage

The quickstarters are not used directly, but triggered via the https://github.com/opendevstack/ods-provisioning-app[provisioning app]. Login there to pick
a quickstarter, give it a name and provision it. The provisioning app delegates the execution to a jenkins job,
located in each quickstarter folder

== Changing existing quickstarters

tbd

== Contributing new quickstarters
If you contribute a new quickstarter / boilerplate - please use the provided `README.adoc` templates

. for a `jenkins-slave` - the https://github.com/opendevstack/ods-quickstarters/blob/master/docs/modules/ROOT/pages/__JENKINS_SLAVE_TEMPLATE_README.adoc[`slave template`]
. for a `boilerplace`- the https://github.com/opendevstack/ods-quickstarters/blob/master/docs/modules/ROOT/pages/__QS_BOILERPLATE_TEMPLATE_README.adoc[`boilerplate`]

