source 'https://rubygems.org' do
  gem 'irb'
  gem 'kitchen-terraform', '~> 5.8.0'
  gem 'test-kitchen'
  gem 'rspec-retry'
  gem 'azure_mgmt_authorization'
  gem 'azure_mgmt_compute'
  gem 'azure_mgmt_storage'
  gem 'azure_mgmt_resources'
  gem 'azure_mgmt_network'
  gem 'azure_mgmt_policy'
  gem 'azure_mgmt_privatedns'
  gem 'azure_mgmt_locks'
  gem 'azure_mgmt_storagecache'
  gem 'azure_mgmt_netapp'
  gem 'azure_mgmt_operational_insights'
end

source 'https://packagecloud.io/cinc-project/stable' do
  gem 'inspec-core'
  gem 'inspec', '4.37.30'
  gem 'cinc-auditor-bin'
  gem 'unf_ext'
  gem 'chef-config'
  gem 'chef-utils'
  gem 'mixlib-install'
  gem 'mixlib-versioning'
end
