source 'https://rubygems.org' do
  if Gem.ruby_version < Gem::Version.new('2.7.0')
    gem 'activesupport', '< 7.0.0'
  end
  gem 'activesupport', '< 7.0.0'
  gem 'irb'
  gem 'kitchen-terraform', '~> 6.1.0'
  gem 'test-kitchen'
  gem 'rspec-retry'
  gem 'azure_mgmt_authorization'
  gem 'azure_mgmt_compute'
  gem 'azure_mgmt_storage'
  gem 'azure_mgmt_resources'
  gem 'azure_mgmt_network'
  gem 'azure_mgmt_policy'
  gem 'azure_mgmt_privatedns'
  gem 'azure_mgmt_locks'
  gem 'azure_mgmt_storagecache'
  gem 'azure_mgmt_netapp'
  gem 'azure_mgmt_operational_insights'
  gem 'azure_mgmt_container_registry'
end

source 'https://packagecloud.io/cinc-project/stable' do
  gem 'inspec-core'
  gem 'inspec', '4.52.9'
  gem 'cinc-auditor-bin'
  gem 'unf_ext'
  gem 'chef-config'
  gem 'chef-utils'
  gem 'mixlib-install'
  gem 'mixlib-versioning'
end
