def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-maven:${odsImageTag}",
) { context ->

  odsQuickstarterStageForkODS(
    context,
    [odsComponent: 'ods-document-generation-svc', branch: "${odsGitRef}"]
  )

  /*
   * see templates in the document generation service
   */
  odsQuickstarterStageCreateOpenShiftResources(
    context,
    [
      directory: "${context.targetDir}/ocp-config",
      selector: 'app=ods-doc-gen-svc'
    ]
  )
}
