def odsGitRef = env.ODS_GIT_REF ?: 'production'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "cd/jenkins-slave-base:${odsImageTag}",
) { context ->

  odsQuickstarterStageForkODS (
  	context, 
  	[ "odsComponent" : "ods-document-generation-svc" ]
  )

  /*
   * see ocp resources in the openshift directory of the document generation service
   */
  odsQuickstarterStageCreateOpenShiftResources(context)
}
